package resume

import (
	"fmt"
	"strings"
	"testing"
)

func TestExtractPDFTextEmptyInput(t *testing.T) {
	got, err := ExtractPDFText(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got != "" {
		t.Fatalf("expected empty text, got %q", got)
	}
}

// buildSampleTextPDF returns a small text-layer PDF generated by rsc.io/pdf
// itself is not possible (it only reads), so we hand-build a minimal PDF.
// If ExtractPDFText cannot extract text from it in this environment, the test
// that uses it is allowed to SKIP rather than FAIL.
func TestExtractPDFTextFromTextPDF(t *testing.T) {
	small := buildSmallTextPDF()
	if small == nil {
		t.Skip("could not build sample PDF bytes")
	}
	got, err := ExtractPDFText(small)
	if err != nil {
		t.Fatalf("extract: %v", err)
	}
	got = strings.ToLower(got)
	if !strings.Contains(got, "hello") {
		t.Skipf("pdf text layer not extractable in this env (got %q)", got)
	}
}

func TestExtractPDFTextRejectsCorruptBytes(t *testing.T) {
	got, err := ExtractPDFText([]byte("not a pdf at all"))
	if err == nil {
		t.Fatalf("expected error for corrupt input, got text %q", got)
	}
}

// buildSmallTextPDF returns a minimal one-page text-layer PDF byte slice.
// Layout: %PDF-1.4 header, 5 objects, xref, trailer. Text drawn: (Hello Resume).
func buildSmallTextPDF() []byte {
	content := "BT /F1 12 Tf 100 700 Td (Hello Resume) Tj ET"
	obj := []string{
		"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
		"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
		"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n",
		fmt.Sprintf("4 0 obj\n<< /Length %d >>\nstream\n%s\nendstream\nendobj\n", len(content), content),
		"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n",
	}
	var b strings.Builder
	b.WriteString("%PDF-1.4\n")
	offsets := []int{0}
	for _, o := range obj {
		offsets = append(offsets, b.Len())
		b.WriteString(o)
	}
	xref := b.Len()
	b.WriteString("xref\n")
	b.WriteString(fmt.Sprintf("0 %d\n", len(obj)+1))
	b.WriteString("0000000000 65535 f \n")
	for i := 1; i <= len(obj); i++ {
		b.WriteString(fmt.Sprintf("%010d 00000 n \n", offsets[i]))
	}
	b.WriteString("trailer\n<< /Size ")
	b.WriteString(fmt.Sprintf("%d", len(obj)+1))
	b.WriteString(" /Root 1 0 R >>\nstartxref\n")
	b.WriteString(fmt.Sprintf("%d\n", xref))
	b.WriteString("%%EOF")
	return []byte(b.String())
}